### ISSUE TITLE
__repr__ recursion error

### ISSUE THREAD

**Issue by mskoenz** [wsmith323/frozenordereddict#1]
Hi!

Just wanted to let you know that I encountered the following issue:
Have a nice day and cheers.

```
Python 3.6.2 (default, Sep 27 2017, 10:12:12)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import frozenordereddict
>>> frozenordereddict.FrozenOrderedDict(a=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mskoenz/.virtualenvs/py3env/lib/python3.6/site-packages/frozenordereddict/__init__.py", line 35, in __repr__
    return '{}({!r})'.format(self.__class__.__name__, self.items())
  File "/Users/mskoenz/.virtualenvs/py3env/bin/../lib/python3.6/_collections_abc.py", line 705, in __repr__
    return '{0.__class__.__name__}({0._mapping!r})'.format(self)
  File "/Users/mskoenz/.virtualenvs/py3env/lib/python3.6/site-packages/frozenordereddict/__init__.py", line 35, in __repr__
    return '{}({!r})'.format(self.__class__.__name__, self.items())
  File "/Users/mskoenz/.virtualenvs/py3env/bin/../lib/python3.6/_collections_abc.py", line 705, in __repr__
    return '{0.__class__.__name__}({0._mapping!r})'.format(self)
  File "/Users/mskoenz/.virtualenvs/py3env/lib/python3.6/site-packages/frozenordereddict/__init__.py", line 35, in __repr__
    return '{}({!r})'.format(self.__class__.__name__, self.items())
...
recursion limit
```

**Comment by wsmith323** [comment]
Resolved in version 1.3.1.
